### ISSUE TITLE
Shouldn't `apply_only` default to true?

### ISSUE THREAD

**Issue by SohumB** [rpadovani/terraform-kubectl-helm-crds#5]
Hi there, thanks for this package.

In using it, though, I've noticed an issue. If you update the crd version, sometimes (every time?) the underlying `kubectl_manifest` will delete and recreate the crds. This can be highly disruptive to the cluster, because that means that actual instances of those CRDs will also be deleted until reconciliation succeeds again. If they're managed in terraform directly, at a minimum this seems to require two `terraform apply`s; but if you have them being managed even by a `helm_release` in terraform or something downstream like flux/cargo, it could take a while before something notices that these ServiceMonitors or karpenter Provisioners (etc.) don't exist.

Looking at the docs for [kubectl_manifest](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/resources/kubectl_manifest), it looks like there's a simple and correct fix: set `apply_only = true`. This seems ideal for CRDs to me.

Thanks!

**Comment by rpadovani** [comment]
Hi @SohumB,
glad you find the package useful! 

It would be nice to understand in which cases the CRD is getting deleted. However, I genuinely understand your use case.
I prefer following the upstream defaults, and setting `apply_only` to true would be a breaking change.

I am going to publish a new version in the next hour or so exposing the flag, defaulted to false. In this way, it is not a breaking change, but you are free to bump the version and set it to true :-)

I hope it is a satisfactory workaround!

**Comment by rpadovani** [comment]
You can now grab version `0.3.0` and set the variable to true! I hope this solves all your problem, kindly let me know if this is not the case!

**Comment by SohumB** [comment]
Thanks! That'll certainly handle the case from my end, because I can set a standard in my org to never use this module without `apply_only: true`.

But I encourage you to rethink what the default should be. It can really cause a major disruption to a cluster to have CRDs disappear, even temporarily. I believe the case that happened to me was when [karpenter](https://karpenter.sh/v0.24.0/upgrade-guide/) changed how they structured their crd files between versions, so the `kubectl_manifest` module saw that as a delete-and-recreate situation.

However, that meant that when that `terraform apply` finished, I had no `karpenter.sh/provisioner`s installed on my cluster — because terraform didn't think it had to recreate them, because they existed when the `terraform apply` started. And since Karpenter treats nodes as owned by their provisioner, that deleted all nodes from my cluster. Until I noticed and ran `terraform apply` again, my cluster was, effectively, completely down.
