### ISSUE TITLE
Proposal to change source of kubectl

### ISSUE THREAD

**Issue by nmofonseca** [rpadovani/terraform-kubectl-helm-crds#8]
Hello @rpadovani ,

Would it be ok to change the kubectl provider to [alekc/kubectl](https://registry.terraform.io/providers/alekc/kubectl/latest).

gavinbunney fork seems to have been abandoned and is also not working properly with K8s 1.27+ as can be seen [here](https://github.com/gavinbunney/terraform-provider-kubectl/issues/270)

Current versions.tf

```hcl
terraform {
  required_providers {
    kubectl = {
      source = "gavinbunney/kubectl"
    }
  }
}
```

Proposed versions.tf

```hcl
terraform {
  required_providers {
    kubectl = {
      source = "alekc/kubectl"
    }
  }
}
```

Thank you so much in advance.

**Comment by rpadovani** [comment]
Hi @nmofonseca, thanks for opening the issue, and for the information about the provider.

I think this is a good idea, however it will recreate all the CRDs, and that is a huge change. I think I will have to bump the major version to mark this change, and hopefully we are not going to break anything. I will work on it this week

**Comment by nmofonseca** [comment]
Hello @rpadovani ,

Thanks for replying and accepting the change. I can also do some testing to confirm it will actually recreate everything. 

Will let you know my findings
